name: Scala CI

on:
  push:
    branches: [ main ]
    tags: ["*"]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run unit tests
        run: sbt test

      - name: Run integration tests
        run: sbt integrationTests

  publish:
    needs: build
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: \${{ github.repository_owner }}
          password: \${{ secrets.CR_TOKEN }} # token is on "github secrets"

      - name: Build and push container image
        run: sbt dockerBuildAndPublish

